version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mlops_logement_api
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: mlops_logement_ui
    ports:
      - "8501:8501"
    depends_on:
      - api