name: CI-CD MLOps Logement

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Entraîner et sauvegarder le modèle
        run: |
          python model/train.py

      - name: Vérifier que le modèle existe
        run: |
          test -f model/model.joblib

      - name: Vérifier que l'API se charge
        run: |
          python -c "from api.main import app; print(app.title)"

      - name: Build Docker API
        run: |
          docker build -t mlops-logement-api -f Dockerfile.

      - name: Build Docker UI
        run: |
          docker build -t mlops-logement-ui -f Dockerfile.